p = "/home/ronald/src/colibri/c/glm53.c"
s = open(p).read()
def rep(old, new, tag):
    global s
    assert old in s, "MISS: " + tag
    assert s.count(old) == 1, "NOT UNIQUE (%d): %s" % (s.count(old), tag)
    s = s.replace(old, new)
    print("ok:", tag)

rep("static double g_t_eg, g_t_cpu; static long g_n_eg, g_n_eg_disp, g_n_cpu, g_n_devloss;",
    "static double g_t_eg, g_t_cpu; static long g_n_eg, g_n_eg_disp, g_n_cpu, g_n_devloss;\nstatic int g_vk_budget2 = 0, g_vk_reg_n2 = 0;", "globals")

rep('            g_vk_budget = getenv("COLI_VK_EXPERTS") ? atoi(getenv("COLI_VK_EXPERTS")) : 0;',
    '            g_vk_budget = getenv("COLI_VK_EXPERTS") ? atoi(getenv("COLI_VK_EXPERTS")) : 0;\n            g_vk_budget2 = getenv("COLI_VK_EXPERTS2") ? atoi(getenv("COLI_VK_EXPERTS2")) : 0;\n            if (g_vk_budget2 > 0 && getenv("COLI_VK_DEV2")) { const char *dv = getenv("COLI_VK_DEV2"); int didx = (!strcmp(dv,"auto")||*dv==0) ? -1 : atoi(dv); if (coli_vk_init_dev2(spv, didx)) fprintf(stderr,"[VK] dev2 ready (expert tier)\\n"); }',
    "init dev2")

rep("    free(cand); if (tmp.base) free(tmp.base);\n    fprintf(stderr, \"[VK] preload: %d heat-ranked experts resident (of %d candidates)\\n\", loaded, (int)n);",
    "    if (g_vk_budget2 > 0 && coli_vk_dev2_available()) {\n        int loaded2 = 0;\n        for (int i = 0; i < (int)n && (g_vk_budget2 <= 0 || loaded2 < g_vk_budget2); i++) {\n            int layer = cand[i].layer, eid = cand[i].eid;\n            void **reg = vk_reg_at(layer, eid);\n            if (reg[0]) continue;\n            expert_read(m, layer, eid, &tmp);\n            Mat gate, up, down; expert_mats(m, &tmp, &gate, &up, &down);\n            ColiVkTensor *t[3] = {0,0,0};\n            if (coli_vk_tensor_ensure2(&t[0], gate.q4, gate.s, gate.fmt, gate.columns, gate.rows, gate.gs) &&\n                coli_vk_tensor_ensure2(&t[1], up.q4, up.s, up.fmt, up.columns, up.rows, up.gs) &&\n                coli_vk_tensor_ensure2(&t[2], down.q4, down.s, down.fmt, down.columns, down.rows, down.gs)) {\n                reg[0]=t[0]; reg[1]=t[1]; reg[2]=t[2]; loaded2++; g_vk_reg_n2++;\n            } else { for (int q=0;q<3;q++) if (t[q]) coli_vk_tensor_free(t[q]); break; }\n        }\n        fprintf(stderr, \"[VK] preload dev2: %d experts resident\\n\", loaded2);\n    }\n    free(cand); if (tmp.base) free(tmp.base);\n    fprintf(stderr, \"[VK] preload: %d heat-ranked experts resident (of %d candidates)\\n\", loaded, (int)n);",
    "preload dev2")

# array declarations + mallocs
rep("    const int maxres = tokens * topk;\n    ColiVkTensor **vg = NULL, **vu = NULL, **vd = NULL;\n    int *vrows = NULL, *voff = NULL, *vtok = NULL;\n    float *vw = NULL, *xk = NULL;\n    int nvk = 0, vtot = 0;\n    if (g_vk_ready) {\n        vg = malloc((size_t)maxres * sizeof(void *));\n        vu = malloc((size_t)maxres * sizeof(void *));\n        vd = malloc((size_t)maxres * sizeof(void *));\n        vrows = malloc((size_t)maxres * sizeof(int));\n        voff = malloc((size_t)maxres * sizeof(int));\n        vtok = malloc((size_t)maxres * sizeof(int));\n        vw = malloc((size_t)maxres * sizeof(float));\n        xk = malloc((size_t)maxres * c->hidden * sizeof(float));\n    }\n#endif",
    "    const int maxres = tokens * topk;\n    ColiVkTensor **vg0 = NULL, **vu0 = NULL, **vd0 = NULL;\n    int *vrows0 = NULL, *voff0 = NULL;\n    ColiVkTensor **vg1 = NULL, **vu1 = NULL, **vd1 = NULL;\n    int *vrows1 = NULL, *voff1 = NULL;\n    int *vtok = NULL; float *vw = NULL, *xk = NULL;\n    int nvk0 = 0, nvk1 = 0, vtot = 0;\n    if (g_vk_ready) {\n        vg0 = malloc((size_t)maxres * sizeof(void *)); vu0 = malloc((size_t)maxres * sizeof(void *)); vd0 = malloc((size_t)maxres * sizeof(void *));\n        vrows0 = malloc((size_t)maxres * sizeof(int)); voff0 = malloc((size_t)maxres * sizeof(int));\n        vg1 = malloc((size_t)maxres * sizeof(void *)); vu1 = malloc((size_t)maxres * sizeof(void *)); vd1 = malloc((size_t)maxres * sizeof(void *));\n        vrows1 = malloc((size_t)maxres * sizeof(int)); voff1 = malloc((size_t)maxres * sizeof(int));\n        vtok = malloc((size_t)maxres * sizeof(int)); vw = malloc((size_t)maxres * sizeof(float));\n        xk = malloc((size_t)maxres * c->hidden * sizeof(float));\n    }\n#endif",
    "array decls")

# collection split
rep('            if (g_vk_ready && vk_reg_at(index, eid)[0] != NULL) {\n                voff[nvk] = vtot;\n                int nr = 0;\n                for (int t = 0; t < tokens; t++) {\n                    float scale = 0.0f;\n                    for (int k = 0; k < topk; k++)\n                        if (chosen[(size_t)t * topk + k] == eid) { scale = weight[(size_t)t * topk + k]; break; }\n                    if (scale == 0.0f) continue;\n                    memcpy(xk + (size_t)vtot * c->hidden, x + (size_t)t * c->hidden, (size_t)c->hidden * sizeof(float));\n                    vtok[vtot] = t; vw[vtot] = scale; vtot++; nr++;\n                }\n                void **reg = vk_reg_at(index, eid);\n                vg[nvk] = (ColiVkTensor *)reg[0]; vu[nvk] = (ColiVkTensor *)reg[1]; vd[nvk] = (ColiVkTensor *)reg[2];\n                vrows[nvk] = nr; nvk++; g_n_eg++;\n                continue;\n            }',
    '                if (g_vk_ready && vk_reg_at(index, eid)[0] != NULL) {\n                    void **reg = vk_reg_at(index, eid);\n                    int off = vtot, nr = 0;\n                    for (int t = 0; t < tokens; t++) {\n                        float scale = 0.0f;\n                        for (int k = 0; k < topk; k++)\n                            if (chosen[(size_t)t * topk + k] == eid) { scale = weight[(size_t)t * topk + k]; break; }\n                        if (scale == 0.0f) continue;\n                        memcpy(xk + (size_t)vtot * c->hidden, x + (size_t)t * c->hidden, (size_t)c->hidden * sizeof(float));\n                        vtok[vtot] = t; vw[vtot] = scale; vtot++; nr++;\n                    }\n                    if (coli_vk_tensor_dev((ColiVkTensor *)reg[0]) == 1) {\n                        voff1[nvk1] = off; vg1[nvk1] = (ColiVkTensor *)reg[0]; vu1[nvk1] = (ColiVkTensor *)reg[1]; vd1[nvk1] = (ColiVkTensor *)reg[2]; vrows1[nvk1] = nr; nvk1++;\n                    } else {\n                        voff0[nvk0] = off; vg0[nvk0] = (ColiVkTensor *)reg[0]; vu0[nvk0] = (ColiVkTensor *)reg[1]; vd0[nvk0] = (ColiVkTensor *)reg[2]; vrows0[nvk0] = nr; nvk0++;\n                    }\n                    g_n_eg++;\n                    continue;\n                }',
    "split collection")

# dispatch both
rep("    if (g_vk_ready && nvk > 0) {\n        double _te0 = prof_now_s();\n        float *yk = malloc((size_t)vtot * c->hidden * sizeof(float));\n        if (yk && coli_vk_expert_group(vg, vu, vd, vrows, nvk, yk, xk)) {\n            for (int c2 = 0; c2 < nvk; c2++) {\n                const int o = voff[c2];\n                for (int r = 0; r < vrows[c2]; r++) {\n                    float *os = out + (size_t)vtok[o + r] * c->hidden;\n                    const float wgt = vw[o + r];\n                    const float *src = yk + (size_t)(o + r) * c->hidden;\n                    for (int d = 0; d < c->hidden; d++) os[d] += wgt * src[d];\n                }\n            }\n            g_n_eg_disp++;\n        } else { g_n_devloss++; }\n        g_t_eg += prof_now_s() - _te0;\n        free(yk);\n    }",
    "    if (g_vk_ready && (nvk0 > 0 || nvk1 > 0)) {\n        double _te0 = prof_now_s();\n        float *yk = malloc((size_t)vtot * c->hidden * sizeof(float));\n        int ok = yk != NULL;\n        if (ok && nvk0 > 0) ok = coli_vk_expert_group(vg0, vu0, vd0, vrows0, nvk0, yk, xk);\n        if (ok && nvk1 > 0) ok = coli_vk_expert_group2(vg1, vu1, vd1, vrows1, nvk1, yk, xk);\n        if (ok) {\n            for (int c2 = 0; c2 < nvk0; c2++) { const int o = voff0[c2]; for (int r = 0; r < vrows0[c2]; r++) { float *os = out + (size_t)vtok[o + r] * c->hidden; const float wgt = vw[o + r]; const float *src = yk + (size_t)(o + r) * c->hidden; for (int d = 0; d < c->hidden; d++) os[d] += wgt * src[d]; } }\n            for (int c2 = 0; c2 < nvk1; c2++) { const int o = voff1[c2]; for (int r = 0; r < vrows1[c2]; r++) { float *os = out + (size_t)vtok[o + r] * c->hidden; const float wgt = vw[o + r]; const float *src = yk + (size_t)(o + r) * c->hidden; for (int d = 0; d < c->hidden; d++) os[d] += wgt * src[d]; } }\n            g_n_eg_disp++;\n        } else { g_n_devloss++; }\n        g_t_eg += prof_now_s() - _te0;\n        free(yk);\n    }",
    "dispatch both")

# frees
rep("#ifdef COLI_VULKAN\n    free(vg); free(vu); free(vd); free(vrows); free(voff); free(vtok); free(vw); free(xk);\n#endif",
    "#ifdef COLI_VULKAN\n    free(vg0); free(vu0); free(vd0); free(vrows0); free(voff0);\n    free(vg1); free(vu1); free(vd1); free(vrows1); free(voff1);\n    free(vtok); free(vw); free(xk);\n#endif",
    "frees")

open(p, "w").write(s)
print("DEV2-SPLIT APPLIED")
